# Generated by Django 5.1.1 on 2024-11-05 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabManagement', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the course', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('jupyterhub_url', models.URLField(help_text='URL of the JupyterHub instance for this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('ta', 'Teaching Assistant')], default='student', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workspace', max_length=255)),
                ('workspace_url', models.URLField(help_text='URL to access this workspace in JupyterHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['email'], name='LabManageme_email_cc5f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='customusermodel',
            index=models.Index(fields=['first_name', 'last_name'], name='LabManageme_first_n_aee87c_idx'),
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(help_text='Course owner/administrator', on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='LabManagement.course'),
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='enrolled_courses', through='LabManagement.CourseMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='LabManagement.course'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(help_text='Users who have access to this workspace', related_name='accessible_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursemembership',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text="User's primary workspace in this course", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_workspaces', to='LabManagement.workspace'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='LabManageme_name_ae3d32_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='LabManageme_created_f6412d_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner'], name='LabManageme_owner_i_92e204_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'owner')},
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['name'], name='LabManageme_name_5bf061_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['course'], name='LabManageme_course__763ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active'], name='LabManageme_is_acti_2d0962_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('name', 'course')},
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['role'], name='LabManageme_role_9126d0_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['joined_at'], name='LabManageme_joined__69b128_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemembership',
            index=models.Index(fields=['is_active'], name='LabManageme_is_acti_123967_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursemembership',
            unique_together={('course', 'user')},
        ),
    ]
